export const products = [
  {
    slug: "kos",
    name: "KOS",
    label: "Korczak Operations System",
    group: "Plataforma",
    description: "Ecossistema operacional B2B da Korczak Technologies.",
  },
  {
    slug: "erp",
    name: "KORCZAK ERP",
    label: "Gestão empresarial",
    group: "Soluções",
    description: "Gestão integrada para empresas.",
  },
  {
    slug: "flow",
    name: "KORCZAK FLOW",
    label: "Automação de processos",
    group: "Soluções",
    description: "Automação e orquestração de fluxos.",
  },
  {
    slug: "ops",
    name: "KORCZAK OPS",
    label: "Operação e produção",
    group: "Soluções",
    description: "Controle de operações e produção.",
  },
  {
    slug: "vision",
    name: "KORCZAK VISION",
    label: "Gestão visual",
    group: "Soluções",
    description: "Gestão visual e computação visual.",
  },
  {
    slug: "connect",
    name: "KORCZAK CONNECT",
    label: "Integrações",
    group: "Soluções",
    description: "Conexão entre sistemas e serviços.",
  },
  {
    slug: "mobile",
    name: "KORCZAK MOBILE",
    label: "Operação móvel",
    group: "Soluções",
    description: "Operação empresarial em mobilidade.",
  },
  {
    slug: "crm",
    name: "KORCZAK CRM",
    label: "Relacionamento",
    group: "Soluções",
    description: "Gestão de relacionamento com clientes.",
  },
  {
    slug: "sales",
    name: "KORCZAK SALES",
    label: "Vendas",
    group: "Soluções",
    description: "Gestão comercial e vendas.",
  },
  {
    slug: "commerce",
    name: "KORCZAK COMMERCE",
    label: "Comércio",
    group: "Soluções",
    description: "Operações de comércio e canais digitais.",
  },
  {
    slug: "scm",
    name: "KORCZAK SCM",
    label: "Supply chain",
    group: "Soluções",
    description: "Gestão da cadeia de suprimentos.",
  },
  {
    slug: "stock",
    name: "KORCZAK STOCK",
    label: "Estoque",
    group: "Soluções",
    description: "Controle e gestão de estoque.",
  },
  {
    slug: "logistics",
    name: "KORCZAK LOGISTICS",
    label: "Logística",
    group: "Soluções",
    description: "Gestão logística e movimentação.",
  },
  {
    slug: "quality",
    name: "KORCZAK QUALITY",
    label: "Qualidade",
    group: "Soluções",
    description: "Gestão e controle da qualidade.",
  },
  {
    slug: "maintenance",
    name: "KORCZAK MAINTENANCE",
    label: "Manutenção",
    group: "Soluções",
    description: "Gestão de manutenção e ativos.",
  },
  {
    slug: "people",
    name: "KORCZAK PEOPLE",
    label: "Pessoas",
    group: "Soluções",
    description: "Gestão de pessoas e operações de equipe.",
  },
  {
    slug: "finance",
    name: "KORCZAK FINANCE",
    label: "Finanças",
    group: "Soluções",
    description: "Gestão financeira empresarial.",
  },
  {
    slug: "fiscal",
    name: "KORCZAK FISCAL",
    label: "Fiscal",
    group: "Soluções",
    description: "Processos e gestão fiscal.",
  },
  {
    slug: "bi",
    name: "KORCZAK BI",
    label: "Business intelligence",
    group: "Dados",
    description: "Informação para decisões empresariais.",
  },
  {
    slug: "analytics",
    name: "KORCZAK ANALYTICS",
    label: "Analytics",
    group: "Dados",
    description: "Análise de dados e indicadores.",
  },
  {
    slug: "documents",
    name: "KORCZAK DOCUMENTS",
    label: "Documentos",
    group: "Soluções",
    description: "Gestão documental.",
  },
  {
    slug: "audit",
    name: "KORCZAK AUDIT",
    label: "Auditoria",
    group: "Soluções",
    description: "Auditoria e rastreabilidade.",
  },
];

export const independentProducts = [
  {
    slug: "korczak-ai",
    name: "Korczak AI",
    label: "Inteligência artificial",
    description: "Inteligência artificial da Korczak Technologies.",
  },
  {
    slug: "aurora-ide",
    name: "Aurora IDE",
    label: "Ambiente de desenvolvimento integrado",
    description:
      "Ambiente de desenvolvimento integrado da Korczak Technologies.",
  },
];
